openapi: 3.0.0
info:
  version: 1.0.0
  title: User API
  description: API documentation for managing users in a Node.js, Express, React.js, and MySQL application.
servers:
  - url: http://localhost:3000
    description: Local server

paths:

  /users:
    get:
      summary: Retrieve all users
      description: Fetch a list of all users from the database.
      responses:
        '200':
          description: List of users.
          content:
            application/json: charset=utf-8
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          X-Powered-By: Express
          Content-Type: application/json; charset=utf-8
          Content-Length: 293
          ETag: W/"125-+2jl2B/c4bVmJIBfaHGHEqWf0dE"
          Date: Date-Time of the response
          Connection: keep-alive
          Keep-Alive: timeout=5

  /user/findUser/{id}:
    get:
      summary: Retrieve a user by ID
      description: Fetch a user from the database by their ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The user ID.
      responses:
        '200':
          description: A single user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found.

  /user/deleteUser/{id}:
    delete:
      summary: Delete user by ID
      description: Delete a user from the database by their ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The user ID.
      responses:
        '200':
          description: A single user deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found.

  /user/UpdateInfoUser/{id}:
    patch:
      summary: Update a user by ID partially
      description: Update a user's info partially from the database by their ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The user ID.
        requestBody:
           {
                "Name":"Name",
                "gender":"Gender",
                "bloodgroup": "Blood group"
            }
            required: true
            Authorization: <jwt-token>
            Content-Type: application/json
            Accept-Encoding: gzip, deflate, br
            Connection: keep-alive
            Content-Length: 102
        required: true
        content:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: A single user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found. 

  /user/UpdateInfo/{id}:
    put:
      summary: Retrieve a user by ID
      description: Fetch a user from the database by their ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The user ID.
          requestBody:
            {
                "Name":"Name",
                "gender":"Gender",
                "bloodgroup": "Blood group"
            }
            required: true
            Authorization: <jwt-token>
            Content-Type: application/json
            Accept-Encoding: gzip, deflate, br
            Connection: keep-alive
            Content-Length: 102
          required: true
          content:
              schema:
                $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: A single user's updation of information.
          content:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found. 

  /user/AddInfo:
    post:
      summary: Add a user's Information
      description: Add a new user to the database.
      requestBody:
          {
            "name":"name",
            "gender":"  Gender",
            "bloodgroup":"Blood group",
            "username":"Username"
          }
        required: true
        Authorization: <jwt-token>
        Content-Type: application/json
        Accept-Encoding: gzip, deflate, br
        Connection: keep-alive
        Content-Length: 102
        content:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: User created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
         name:
          type: string
          example: John Doe
        gender:
          type: string
          example: Male
        bloodgroup:
          type: string
          example: ab +/-ve
        username:
          type: string
          example: Yash123       

    UserInput:
      type: object
      properties:
        name:
          type: string
          example: John Doe
        gender:
          type: string
          example: Male
        bloodgroup:
          type: string
          example: ab +/-ve
        username:
          type: string
          example: Yash123

